### ISSUE TITLE
The value of speed is never 10 mbps

### ISSUE THREAD

**Issue by AiswariyaP** [vinayakkulkarni/vue-identify-network#390]
Why the value of speed is capped as 10mbps. Is there any way to override this property since 10mbps doesn't make any sense in my case.

**Comment by vinayakkulkarni** [comment]
The reason for this is because the plugin uses the native `navigator` to identify the network speed(s).

Refer: https://github.com/vinayakkulkarni/vue-identify-network/blob/master/src/VueIdentifyNetwork.vue#L44
